const mongoose = require("mongoose");

const sundaramSchema = new mongoose.Schema(
  {
    layoutApproval: String,
    approvedNumber1: String,
    approvedDate1: String,
    approvedAuthority1: String,
    planningPermit: String,
    approvedNumber2: String,
    approvedDate2: String,
    approvedAuthority2: String,
    buildingPermit: String,
    approvedNumber3: String,
    approvedDate3: String,
    approvedAuthority3: String,
    civicStatus: String,
    propertyIdentifiedBy: String,
    plotDemarcation: String,
    propCharacteristic: String,
    shapeOfLand: String,
    typeOfRoad1: String,
    roadWidth1: String,
    typeOfRoad2: String,
    roadWidth2: String,
    reportedOwner: String,
    ebServiceNo: String,
    docNorth: String,
    docSouth: String,
    docEast: String,
    docWest: String,
    siteNorth: String,
    siteSouth: String,
    siteEast: String,
    siteWest: String,
    matchesDoc: String,

    // Photos
    frontElevation: [String],
    doorPlotNo: [String],
    roadView: [String],
    hall: [String],
    kitchen: [String],
    bedRoom: [String],
    toilet: [String],
    others: [String],

    // Development Info
    developmentLocality: String,
    surroundingUsage: [String],
    classification: String,
    facilities: [String],
    waterSupply: [String],
    sanitarySystem: [String],

    // Caution / Legal / Planning
    caution_property: String,
    usage_master_plan: String,
    usage_site: String,
    marketability: String,
    rental_value: String,
    factor_enhancing: String,
    factor_affecting: String,

    // Building Specifications
    building_spec_1: String,
    building_spec_2: String,
    total_units: String,
    construction_type: String,
    structure: String,
    roof: String,
    flooring: [String],
    details_of_rooms: String,
    stage_of_construction: String,
    year_of_construction: String,
    total_life: String,
    age_of_building: String,
    residual_age: String,
    natural_protection: [String],

    // Valuation
    extent_of_land: String,
    unit: String,
    land_rate_range: String,
    rate_adopted: String,
    land_value: String,
    guideline_value: String,
    building_area: String,
    building_unit: String,
    building_value: String,
    carpet_area: String,
    amenities_cost: String,
    total_property_value: String,
    realizable_value: String,
    forced_sale_value: String,
    present_value: String,
    property_outlook: String,
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("sundaram", sundaramSchema);
