export const banks = [
  { name: "Agriwise", logo: "agriwise.png" },
  //   { name: "All Bank", logo: "allbank.jpg" },
  { name: "AU Small Finance Bank", logo: "Au.png" },
  { name: "Bajaj", logo: "bajaj.png" },
  { name: "Bajaj Ameriya Bank", logo: "bajaj.png" },
  { name: "Chola", logo: "chola.png" },
  { name: "DMI Finance", logo: "dmifinance.png" },
  { name: "Federal Bank", logo: "fed.png" },
  { name: "Hero Fincorp", logo: "hero.png" },
  { name: "Home First", logo: "homefrist.png" },
  { name: "Home First Trench", logo: "homefrist.png" },
  { name: "ICICI", logo: "ici.png" },
  { name: "ICICI HFC", logo: "ici.png" },
  { name: "IDFC First Bank", logo: "idfc.png" },
  { name: "Manappuram", logo: "manipuram.png" },
  { name: "Piramal", logo: "pirmal.png" },
  { name: "PiramalNPA Form", logo: "pirmal.png" },
  { name: "Profectus", logo: "proefectus.png" },
  { name: "Protium", logo: "protium.png" },
  { name: "Aditya", logo: "aditya.png" },
  { name: "Samasta", logo: "samsata.png" },
  { name: "Shriram", logo: "shriram.png" },
  { name: "Shubham", logo: "shubham.png" },
  { name: "Sundaram", logo: "sundaram.png" },
  { name: "Suryoday", logo: "suryoday.png" },
  { name: "Utkarsh", logo: "utkarsh.png" },
];
